Python(39928,0x7fffba8553c0) malloc: *** mach_vm_map(size=9007199254740992) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
{'basis_gates_option': 2, 'qasm_file': './testcases/q3sat.qasm', 'return_measured_state': 1, 'report_after_every_step': 1}




 > ANALYZING ./testcases/q3sat.qasm

*********state after step:1*********
layer summary:
 X(conj[9])*H(var[6])*X(conj[6])*X(conj[13])*X(conj[19])*H(var[2])*X(conj[1])*X(conj[8])*H(var[9])*X(conj[5])*X(conj[12])*X(conj[18])*H(var[5])*X(conj[0])*H(var[1])*H(var[8])*X(conj[4])*X(conj[11])*X(conj[17])*H(var[4])*X(conj[15])*X(conj[3])*X(conj[10])*X(conj[16])*H(var[7])*X(conj[7])*X(conj[14])*X(conj[20])*H(var[3])*X(conj[2])
state summary:
 
Traceback (most recent call last):
  File "sympy_executor.py", line 90, in <module>
    math_execute(args, circuit)
  File "/Users/liup/quantum/qiskit_dec_2017/qiskit/tools/sympy_executor/math_executor.py", line 211, in math_execute
    print(matrix_with_header(represent(q), getHeaderKet(qid2qubit)))
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/represent.py", line 165, in represent
    result = represent(expr.args[0], **options)
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/represent.py", line 207, in represent
    result = represent(expr.args[-1], **options)
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/represent.py", line 145, in represent
    return expr._represent(**options)
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/qexpr.py", line 387, in _represent
    result = self._represent_default_basis(**options)
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/qubit.py", line 189, in _represent_default_basis
    return self._represent_ZGate(None, **options)
  File "/usr/local/lib/python3.6/site-packages/sympy/physics/quantum/qubit.py", line 200, in _represent_ZGate
    result = [0]*(2**self.dimension)
MemoryError
